
stages:
  - build

build:
  image: fpco/stack-build:lts-12.26
  stage: build
  script:
    - stack install
    - stack test

# does not work yet, work in progress
build-static-binary:on-schedule:
  image: nixos/nix
  stage: build
  only:
    - schedule
  script:
    - $(nix-build --no-link -A fullBuildScript)
